---
- name: update
  hosts: qb_rhel
  gather_facts: false
  tasks:
  - name: Update
    command: "yum -y update"

- name: Install Apache on web and start service
  hosts: qb_rhel
  gather_facts: false
  tasks: 
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: update port
      command: "sed -i 's/Listen 80/Listen 8081/g' /etc/httpd/conf/httpd.conf"
    - name: Start Apache service
      systemd: 
        name: httpd
        state: started
#    - name: Open TCP 8081 and 443
#      firewalld:
#        service: "{{ item }}"
#        permanent: yes
#        state: enabled
#        immediate: yes
#      loop: 
#        - 8081
#        - https

- name: Install mariadb and start service
  hosts: qb_rhel
  gather_facts: false
  tasks: 
    - name: Install mariadb-server
      yum: 
        name: mariadb-server
        state: latest
    - name: Start mariadb service
      systemd: 
        name: mariadb
        state: started
        enabled: yes
...
