---
- name: clear env
  hosts: qb_group3
  gather_facts: false
  tasks:
  - name: uninstall mariadb
    command: "yum -y erase mariadb-server"
  - name: uninstall apache
    command: "yum -y erase httpd"
...
